spring.application.name=demo

server.tomcat.accesslog.enabled=true

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.url=jdbc:postgresql://dpg-d8md07jtqb8s73bu9fq0-a.oregon-postgres.render.com/database_9pk6
spring.datasource.username=database_9pk6_user
spring.datasource.password=dgT5BDdjojVMDTrmwJv4LKjurlIS8qnq